all: exam1 exam2 exam3 exam4 mem1
exam1: exam1.c
	g++ -o exam1 exam1.c
exam2: exam2.c
	g++ -o exam2 exam2.c
exam3: exam3.c
	g++ -o exam3 exam3.c
exam4: exam4.c
	g++ -o exam4 exam4.c
mem1: mem1.c
	g++ -o mem1 mem1.c
clean:
	rm *.o exam1 exam2 exam3 exam4 mem1
